version: '3'
services:
  router:
    container_name: router
    image: pankona/router
    build:
      context: .
      dockerfile: ./config/router/Dockerfile
    ports:
      - "8080:80"
  hashira-frontend:
    container_name: hashira-frontend
    image: pankona/hashira-frontend
    build:
      context: .
      dockerfile: ./config/hashira-frontend/Dockerfile
  hashira-auth:
    container_name: hashira-auth
    image: pankona/hashira-auth
    build:
      context: .
      dockerfile: ./config/hashira-auth/Dockerfile
    environment:
      HASHIRA_AUTH_SERVER_PORT: "80"
  hashira-api:
    container_name: hashira-api
    image: pankona/hashira-api
    build:
      context: .
      dockerfile: ./config/hashira-api/Dockerfile
    environment:
      HASHIRA_API_SERVER_PORT: "80"
